<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Elegant Black Dress',
                'description' => 'A timeless black dress perfect for any occasion. Made with premium fabric that breathes and moves with you.',
                'price' => 129.99,
                'original_price' => 179.99,
                'category' => 'fashion',
                'image' => 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=500',
                'sku' => 'SKU-001',
                'stock' => 50,
                'is_active' => true,
                'is_new' => true,
                'is_sale' => true,
                'featured' => true,
                'rating' => 5,
                'reviews_count' => 24,
                'sizes' => json_encode(['XS', 'S', 'M', 'L', 'XL', 'XXL']),
                'colors' => json_encode(['Black', 'Navy', 'Burgundy']),
            ],
            [
                'name' => 'White Minimalist Blazer',
                'description' => 'Modern white blazer with clean lines. Perfect for business casual and professional settings.',
                'price' => 159.99,
                'original_price' => 199.99,
                'category' => 'fashion',
                'image' => 'https://images.unsplash.com/photo-1550314471-c5b763d2e5a1?w=500',
                'sku' => 'SKU-002',
                'stock' => 35,
                'is_active' => true,
                'is_new' => true,
                'is_sale' => false,
                'featured' => true,
                'rating' => 4,
                'reviews_count' => 18,
                'sizes' => json_encode(['XS', 'S', 'M', 'L', 'XL']),
                'colors' => json_encode(['White', 'Beige', 'Black']),
            ],
            [
                'name' => 'Classic Denim Jeans',
                'description' => 'Comfortable and durable denim jeans with a classic fit. Made with 100% premium cotton.',
                'price' => 89.99,
                'original_price' => 119.99,
                'category' => 'fashion',
                'image' => 'https://images.unsplash.com/photo-1542272604-787c62d465d1?w=500',
                'sku' => 'SKU-003',
                'stock' => 100,
                'is_active' => true,
                'is_new' => false,
                'is_sale' => true,
                'featured' => true,
                'rating' => 5,
                'reviews_count' => 45,
                'sizes' => json_encode(['28', '30', '32', '34', '36', '38', '40']),
                'colors' => json_encode(['Light Blue', 'Dark Blue', 'Black']),
            ],
            [
                'name' => 'Leather Handbag',
                'description' => 'Sophisticated leather handbag with premium finish. Perfect for work and casual outings.',
                'price' => 199.99,
                'original_price' => null,
                'category' => 'accessories',
                'image' => 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500',
                'sku' => 'SKU-004',
                'stock' => 25,
                'is_active' => true,
                'is_new' => true,
                'is_sale' => false,
                'featured' => false,
                'rating' => 5,
                'reviews_count' => 12,
                'sizes' => json_encode(['One Size']),
                'colors' => json_encode(['Black', 'Brown', 'Tan']),
            ],
            [
                'name' => 'Silk Scarf',
                'description' => 'Beautiful silk scarf with intricate patterns. Adds elegance to any outfit.',
                'price' => 49.99,
                'original_price' => 79.99,
                'category' => 'accessories',
                'image' => 'https://images.unsplash.com/photo-1514432324607-2e467f4af445?w=500',
                'sku' => 'SKU-005',
                'stock' => 60,
                'is_active' => true,
                'is_new' => true,
                'is_sale' => true,
                'featured' => true,
                'rating' => 4,
                'reviews_count' => 22,
                'sizes' => json_encode(['One Size']),
                'colors' => json_encode(['Blue', 'Red', 'Green', 'Yellow']),
            ],
            [
                'name' => 'Ankle Boot',
                'description' => 'Stylish ankle boots with comfortable heel. Perfect for all seasons.',
                'price' => 139.99,
                'original_price' => 179.99,
                'category' => 'shoes',
                'image' => 'https://images.unsplash.com/photo-1548062407-0d3ba4c9d76c?w=500',
                'sku' => 'SKU-006',
                'stock' => 40,
                'is_active' => true,
                'is_new' => false,
                'is_sale' => true,
                'featured' => true,
                'rating' => 5,
                'reviews_count' => 31,
                'sizes' => json_encode(['5', '6', '7', '8', '9', '10', '11', '12']),
                'colors' => json_encode(['Black', 'Brown', 'Tan']),
            ],
            [
                'name' => 'Casual Sneaker',
                'description' => 'Comfortable and stylish sneaker for everyday wear. Perfect for casual outings and workouts.',
                'price' => 99.99,
                'original_price' => 139.99,
                'category' => 'shoes',
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
                'sku' => 'SKU-007',
                'stock' => 80,
                'is_active' => true,
                'is_new' => true,
                'is_sale' => true,
                'featured' => true,
                'rating' => 4,
                'reviews_count' => 56,
                'sizes' => json_encode(['5', '6', '7', '8', '9', '10', '11', '12']),
                'colors' => json_encode(['White', 'Black', 'Gray', 'Pink']),
            ],
            [
                'name' => 'Summer T-Shirt',
                'description' => 'Lightweight and breathable t-shirt perfect for summer. Made with soft cotton blend.',
                'price' => 39.99,
                'original_price' => 59.99,
                'category' => 'fashion',
                'image' => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500',
                'sku' => 'SKU-008',
                'stock' => 150,
                'is_active' => true,
                'is_new' => false,
                'is_sale' => true,
                'featured' => false,
                'rating' => 4,
                'reviews_count' => 39,
                'sizes' => json_encode(['XS', 'S', 'M', 'L', 'XL', 'XXL']),
                'colors' => json_encode(['White', 'Black', 'Blue', 'Red', 'Green']),
            ],
            [
                'name' => 'Designer Sunglasses',
                'description' => 'Stylish designer sunglasses with UV protection. Perfect for protecting your eyes in style.',
                'price' => 179.99,
                'original_price' => 249.99,
                'category' => 'accessories',
                'image' => 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500',
                'sku' => 'SKU-009',
                'stock' => 45,
                'is_active' => true,
                'is_new' => true,
                'is_sale' => true,
                'featured' => true,
                'rating' => 5,
                'reviews_count' => 28,
                'sizes' => json_encode(['One Size']),
                'colors' => json_encode(['Black', 'Brown', 'Gold']),
            ],
            [
                'name' => 'Wool Coat',
                'description' => 'Premium wool coat for winter. Provides warmth and comfort while maintaining style.',
                'price' => 299.99,
                'original_price' => 399.99,
                'category' => 'fashion',
                'image' => 'https://images.unsplash.com/photo-1539533057687-c8a0dfe30986?w=500',
                'sku' => 'SKU-010',
                'stock' => 20,
                'is_active' => true,
                'is_new' => false,
                'is_sale' => true,
                'featured' => true,
                'rating' => 5,
                'reviews_count' => 15,
                'sizes' => json_encode(['XS', 'S', 'M', 'L', 'XL']),
                'colors' => json_encode(['Black', 'Camel', 'Gray']),
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
